config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  get 'admin/', to: 'admin#index'
  get 'admin/new_mail', to: 'admin#new_mail'
  post 'admin/send_mail', to: 'admin#send_mail'

  get 'rgs', to: 'rgs#index'
  get 'rgs/:serial_code', to: 'rgs#index'
  post 'rgs', to: 'rgs#rgs'
  
  resources :cards do
    get 'edit_title', to: 'cards#edit_title'
    get 'edit_auther_name', to: 'cards#edit_auther_name'
    get 'edit_content', to: 'cards#edit_content'
    get 'edit_card_img', to: 'cards#edit_card_img'
    resources :contents
    resources :musics do
      post 'moveup', to: 'musics#moveup'
      post 'movedown', to: 'musics#movedown'
      post 'music_destroy', to: 'musics#music_destroy'
    end
    resources :license_groups do
      get 'download', to: 'license_groups#download'
      get 'download_front', to: 'license_groups#download_front'
      get 'download_back', to: 'license_groups#download_back'
    end
  end
  resources :downloads do
    resources :download_musics
    get 'mp3_zip', to: 'download_musics#mp3_zip'
    get 'flac_zip', to: 'download_musics#flac_zip'
    resources :download_contents
  end
  devise_for :users
  root to: "home#index"
  get 'topic', to: 'home#topic'
  get 'use_card', to: 'home#use_card'
  get 'use_label', to: 'home#use_label'
  get 'use_make_card', to: 'home#use_make_card'
  get 'question', to: 'home#question'
  get 'contact', to: 'home#contact'
  post :contact, to: 'home#contact_confirm'
  post 'contact_create', to: 'home#contact_create'
  get 'contact_complete', to: 'home#contact_complete'
  get 'terms_of_service', to: 'home#terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def index
    @licenses = current_user.licenses
  end

  def show
    licenses = current_user.licenses
    @license = licenses.find(params[:id])
    @card = @license.license_group.card
    @musics = @card.musics.order(track_number: "ASC")
  end

  def destroy
    licenses = current_user.licenses
    license = licenses.find(params[:id])
    license.update(user_id: nil)
    redirect_to downloads_url, notice: "登録を解除しました。"
  end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/index.html.erb
<main>
  <div class="container">
    <h2 class="my-3" style="color: #2196f3;"><span class="material-icons">get_app</span>ダウンロード</h2>
    <div class="d-md-none">
      <% @licenses.each do |license| %>
      <div class="row mb-2 border-top pt-2">
        <div class="col-4">
          <div class="pr-1">
            <%= image_tag license.license_group.card.card_img.variant(resize:'140x100').processed, class: "img-thumbnail", style: "object-fit: contain;" if license.license_group.card.card_img.attached? %>
          </div>
        </div>
        <div class="col-8">
          <h4><%=license.license_group.card.title%></h4>
          <p style="margin-bottom: 3px;"><%=license.license_group.card.auther_name%></p>
          <div class="text-right">
            <%= link_to "詳細", download_path(license) ,class: "btn btn-primary btn-outline btn-sm"%>
            <%#= link_to "ダウンロード", download_path(license.license_group.card) ,class: "btn btn-primary btn-outline btn-sm"%>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="d-none d-md-block">
      <div class="row">
      <% @licenses.each do |license| %>
        <div class="col-md-4 mb-3">
          <div class="card" style="max-width: 25rem;">
            <%= image_tag license.license_group.card.card_img.variant(resize:'350x200').processed, class: "card-img-top", style: "object-fit: contain;height: 200px;" if license.license_group.card.card_img.attached? %>
            <div class="card-body">
              <h4 class="card-title"><%=license.license_group.card.title%></h4>
              <h6 class="card-subtitle"><%=license.license_group.card.auther_name%></h6>
              <p class="card-text"></p>
              <div class="text-right">
                <%= link_to "詳細", download_path(license) ,class: "btn btn-primary btn-outline btn-sm"%>
                <%= link_to "登録を解除", download_path(license) ,class: "btn btn-danger btn-outline btn-sm", method: :delete %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <% if @licenses.empty? %>
    <div class="text-center my-5">
      <h3><span class="material-icons" style="font-size: 4rem;">help</span></h3>
      <h4>ダウンロードをするには、左下よりカードを登録します。</h4>
    </div>
    <% end %>
    <div class="text-right mb-3">
      <%=link_to "新しいカードを登録する", rgs_path, class: "btn btn-primary btn-raised"%>
    </div>
  </div>
</main>

app/views/downloads/show.html.erb
<main>
  <div class="container mb-5">
    <h2 class="my-3"><%=@card.title%></h2>
    <h5><%=@card.auther_name%></h5>
    <%=link_to "一覧画面に戻る", downloads_path, class: "btn btn-primary btn-outline"%>
    <div class="text-center mb-3">
      <%= image_tag @card.card_img, style: "max-width: 100%; max-height: 379px;" if @card.card_img.attached? %>
    </div>
    <%if @musics.any?%>
    <section>
      <h4>音楽・音声</h4>
      <table class="table table-hover" style="table-layout: fixed;">
        <tbody>
        <%@musics.each do |music|%>
          <tr>
            <td width="50">
              <span style="font-weight: bold;"><%=music.track_number%></span>
            </td>
            <td><%#=music.music.filename.to_s%>
              <div>
                <span style="font-weight: bold;"><%=music.title%></span><br>
              </div>
              <div>
                <span style="font-size: 14px;"><%=music.artist_name%></span>
              </div>
            </td>
            <td width="88">
              <div class="text-right">
                <%#=music.music.content_type%>
                <%=link_to '再生', download_download_music_path(@license, music), remote: true, class: "btn btn-primary btn-outline"%>
              </div>
            </td>
          </tr>
        <%end%>
        </tbody>
      </table>
      <div class="text-right">
        <%=link_to download_flac_zip_path(@license), remote: true, class: "btn btn-primary btn-outline" do %>
          一括ダウンロード(flac)
          <div id="flac-download-spinner" class="d-none spinner-border spinner-border-sm" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        <% end %>
        <%=link_to download_download_musics_path(@license), remote: true, class: "btn btn-primary btn-outline" do %>
          一括ダウンロード(wav)
          <div id="wav-download-spinner" class="d-none spinner-border spinner-border-sm" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        <% end %>
        <%=link_to download_mp3_zip_path(@license), remote: true, class: "btn btn-primary btn-outline" do %>
          一括ダウンロード(mp3)
          <div id="mp3-download-spinner" class="d-none spinner-border spinner-border-sm" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        <% end %>
      </div>
      <div class="text-right mb-3">
        ※ダウンロードには数分かかります。
      </div>
    </section>
    <%end%>
    <%if @card.contents.any?%>
    <section>
      <h4>コンテンツ</h4>
      <table class="table table-hover">
        <tbody>
        <%@card.contents.each do |content|%>
          <tr>
            <td><%=content.content.filename.to_s%></td>
            <td>
              <div class="text-right">
                <%=content.content.content_type%>
                <%=link_to 'ダウンロード', download_download_content_path(@license, content), :target=>["_blank"], class: "btn btn-primary btn-outline"%>
              </div>
            </td>
          </tr>
        <%end%>
        </tbody>
      </table>
      <div class="text-right mb-3">
        <%=link_to "一括ダウンロード" , download_download_contents_path(@license, format: :zip), class: "btn btn-primary btn-outline"%>
      </div>
    </section>
    <%end%>
  </div>
</main>
<div class="d-none" id="player_container">
  <div class="scrollbar" id="scrollbar"></div>
  <div class="scrollbar-glay" id="scrollbar_glay"></div>
  <audio src="#" id="audio"></audio>
  <div class="player-title" id="player_title"></div>
  <div class="player-artist" id="player_artist"></div>
  <button class="now" id="play"><span class="material-icons">play_arrow</span></button>
  <button class="d-none" id="pause"><span class="material-icons">pause</span></button>
</div>
<%= javascript_pack_tag 'player', 'data-turbolinks-track': 'reload' %>
<%# TODO:CDNではなくてWEBpackerで読み込みたい %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.7.1/jszip.min.js" integrity="sha512-xQBQYt9UcgblF6aCMrwU1NkVA7HCXaSN2oq0so80KO+y68M+n64FOcqgav4igHe6D5ObBLIf68DWv+gfBowczg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.min.js" integrity="sha512-csNcFYJniKjJxRWRV1R7fvnXrycHP6qDR21mgz1ZP55xY5d+aHLfo9/FcGDQLfn2IfngbAHd8LdfsagcCqgTcQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>