config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  get 'admin/', to: 'admin#index'
  get 'admin/new_mail', to: 'admin#new_mail'
  post 'admin/send_mail', to: 'admin#send_mail'

  get 'rgs', to: 'rgs#index'
  get 'rgs/:serial_code', to: 'rgs#index'
  post 'rgs', to: 'rgs#rgs'
  
  resources :cards do
    get 'edit_title', to: 'cards#edit_title'
    get 'edit_auther_name', to: 'cards#edit_auther_name'
    get 'edit_content', to: 'cards#edit_content'
    get 'edit_card_img', to: 'cards#edit_card_img'
    resources :contents
    resources :musics do
      post 'moveup', to: 'musics#moveup'
      post 'movedown', to: 'musics#movedown'
      post 'music_destroy', to: 'musics#music_destroy'
    end
    resources :license_groups do
      get 'download', to: 'license_groups#download'
      get 'download_front', to: 'license_groups#download_front'
      get 'download_back', to: 'license_groups#download_back'
    end
  end
  resources :downloads do
    resources :download_musics
    get 'mp3_zip', to: 'download_musics#mp3_zip'
    get 'flac_zip', to: 'download_musics#flac_zip'
    resources :download_contents
  end
  devise_for :users
  root to: "home#index"
  get 'topic', to: 'home#topic'
  get 'use_card', to: 'home#use_card'
  get 'use_label', to: 'home#use_label'
  get 'use_make_card', to: 'home#use_make_card'
  get 'question', to: 'home#question'
  get 'contact', to: 'home#contact'
  post :contact, to: 'home#contact_confirm'
  post 'contact_create', to: 'home#contact_create'
  get 'contact_complete', to: 'home#contact_complete'
  get 'terms_of_service', to: 'home#terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_one_attached :card_img
  has_many :license_groups, dependent: :destroy
  has_many :contents, dependent: :destroy
  has_many :musics, dependent: :destroy

  validates :title, presence: true
  validates :format, presence: true
  validates :auther_name, presence: true
  validates :card_img, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/models/content.rb
class Content < ApplicationRecord
  has_one_attached :content

  validates :content, presence: true
end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :license_group
end

app/models/license_group.rb
class LicenseGroup < ApplicationRecord
  has_many :licenses, dependent: :destroy
  belongs_to :card

  validates :number_of_licenses, presence: true, numericality: {only_integer: true, less_than: 10000}
end

app/models/music.rb
class Music < ApplicationRecord
  has_one_attached :music
  has_one_attached :music_mp3
  has_one_attached :music_flac

  validates :title, presence: true
  validates :music, presence: true, blob: { content_type: ['audio/wav', 'audio/x-wav'] }
  validates :music, presence: true
  validates :artist_name, presence: true
end

app/models/serial_tmp.rb
class SerialTmp < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :cards
  has_many :licenses
  validates :username, presence: true

  validate :check_number_of_creator

  # フォームで悪意のある送り方をされた場合
  def check_number_of_creator
    if creator?
      errors.add(:base ,"現在プレリリース期間の為カード制作用アカウントの作成は、お問い合わせより承っております。")
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :if_not_admin

  def index
  end

  def new_mail
  end

  def send_mail
    users = User.all
    users.each do |user|
      AdminMailer.allusers(params[:subject], params[:content], user.email).deliver_now
    end
    redirect_to admin_path, notice: "送信されました"
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    redirect_to "https://www.share-cards.com/", status: 301 if root_url == "https://share-cards.herokuapp.com/"
  end
  def topic
  end

  def use_card
  end

  def use_label
  end
  
  def use_make_card
  end
  
  def contact
    @contact = Contact.new()
  end

  def contact_confirm
    @contact = Contact.new(contact_params)
    render :contact if @contact.invalid?
  end

  def contact_create
    @contact = Contact.new(contact_params)

    if params[:back].present?
      render :contact
      return
    end

    @contact.save!

    ContactMailer.contact(@contact.title, @contact.email, @contact.content).deliver_now
    
    redirect_to contact_complete_path, notice: "送信されました。"
  end

  def contact_complete
    
  end

  def terms_of_service
  end

  def privacy_policy
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :email, :content)
  end
end

app/controllers/rgs_controller.rb
class RgsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if params[:serial_code]
      serial_code =[] 
      params[:serial_code].scan(/.{1,#{4}}/).each_with_index do |s, i|
        serial_code[i] = s
      end
      @serial_tmp = SerialTmp.new(serial_code1: serial_code[0], serial_code2: serial_code[1], serial_code3: serial_code[2], serial_code4: serial_code[3])
    elsif
      @serial_tmp = SerialTmp.new()
    end
  end

  def rgs
    serial_codes = SerialTmp.new(serial_params)
    serial_code = serial_codes.serial_code1 + serial_codes.serial_code2 + serial_codes.serial_code3 + serial_codes.serial_code4
    if current_user
      # ログイン状態の場合
      if License.where(serial_code: serial_code).exists?
        license = License.find_by(serial_code: serial_code)
        if license.user_id?
          redirect_to rgs_url, alert: "既に使用されたコードです"
        else
          # ライセンスの更新処理
          license = License.find_by(serial_code: serial_code)
          license.update(user_id: current_user.id)
          redirect_to downloads_url, notice: "「#{license.license_group.card.title}」を登録しました。詳細ページからダウンロード出来ます。"
        end
      else
        redirect_to rgs_url, alert: "無効なシリアルコードです"
      end
    else
      # ログイン状態でない場合
      if License.where(serial_code: serial_code).exists?
        license = License.find_by(serial_code: serial_code)
        if license.user_id?
          redirect_to rgs_url, alert: "既に使用されたコードです"
        else
          # ライセンスの更新処理
          @remaining_number = 3 - license.download_times;
          if @remaining_number > 0
            # ダウンロード処理
            license.increment!(:download_times)
            @card = license.license_group.card
            @title = @card.title
            @contentfiles = @card.contents.map{ |content| [url_for(content.content), content.content.filename.to_s] }
            @files = @card.musics.map{ |music| [url_for(music.music_mp3), "#{music.track_number}-#{music.title}-#{music.artist_name}.mp3"] }
          else
            redirect_to rgs_url, alert: "ダウンロード回数を超過しました。ログインする事で制限を解除出来ます。"
          end
        end
      else
        redirect_to rgs_url, alert: "無効なシリアルコードです"
      end
    end
  end

  private

  def serial_params
    params.require(:serial_tmp).permit(:serial_code1, :serial_code2, :serial_code3, :serial_code4)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/rgs_helper.rb
module RgsHelper
end

app/views/admin/index.html.erb
<main>
  <div class="container ">
    <h1 class="my-5">管理者メニュー</h1>
    <p>管理者のみがログインできます。</p>
    <%= link_to  "メールの一斉送信", admin_new_mail_path, class: "btn btn-primary btn-outline btn-sm" %>
  </div>
</main>

app/views/admin/new_mail.html.erb
<main>
  <div class="container">
    <h1 class="my-5">メールの一斉送信</h1>
    <%= link_to  "戻る", admin_path, class: "btn btn-primary btn-outline" %>
    <%= form_with url: admin_send_mail_path do |f| %>
      <div class="form-group">
        <%= f.label :subject %>
        <%= f.text_field :subject, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control" %>
      </div>
      <div class="text-right">
        <%= f.submit "送信する",class: 'btn btn-primary btn-raised'%>
      </div>
    <% end %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ShareCards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="padding-top: 60px;">
    <header class="navbar navbar-light fixed-top navbar-expand-lg" style="background-color: white;">
      <%= link_to image_tag("logo.png", class: "navbar-brand", style: "height: 45px;"), root_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "トップページ", root_path,class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "トピックス", topic_path,class: "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle active" id="navbarDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            使い方
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenu">
              <%= link_to "カードを貰った", use_card_path, class: "dropdown-item" %>
              <%= link_to "ラベルを貰った", use_label_path, class: "dropdown-item" %>
              <%= link_to "カード・ラベルを作成", use_make_card_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to "よくある質問", question_path,class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "お問い合わせ", contact_path,class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "利用規約", terms_of_service_path,class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "プライバシーポリシー", privacy_policy_path,class: "nav-link"%>
          </li>
          <li class="nav-item active mr-2">
            <%= link_to "ダウンロード(カードをお持ちの場合)", downloads_path,class: "btn btn-raised btn-primary"%>
          </li>
          <li class="nav-item active">
            <%= link_to "カードを作る", cards_path,class: "btn btn-outline btn-primary"%>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle active" id="navbarDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-transform: none;"><%=current_user.username%></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenu">
              <%= link_to "ユーザー詳細", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link active" %>
          </li>
          <% end %>
        </ul>
      </div>
    </header>
    <% if alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <% if notice.present? %>
    <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <%= yield %>
    <footer>
      <div class="container text-center">
        <p><small>Copyright &copy;2020 ShareCards, All Rights Reserved.</small></p>
      </div>
    </footer>
  </body>
</html>