config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  get 'admin/', to: 'admin#index'
  get 'admin/new_mail', to: 'admin#new_mail'
  post 'admin/send_mail', to: 'admin#send_mail'

  get 'rgs', to: 'rgs#index'
  get 'rgs/:serial_code', to: 'rgs#index'
  post 'rgs', to: 'rgs#rgs'
  
  resources :cards do
    get 'edit_title', to: 'cards#edit_title'
    get 'edit_auther_name', to: 'cards#edit_auther_name'
    get 'edit_content', to: 'cards#edit_content'
    get 'edit_card_img', to: 'cards#edit_card_img'
    resources :contents
    resources :musics do
      post 'moveup', to: 'musics#moveup'
      post 'movedown', to: 'musics#movedown'
      post 'music_destroy', to: 'musics#music_destroy'
    end
    resources :license_groups do
      get 'download', to: 'license_groups#download'
      get 'download_front', to: 'license_groups#download_front'
      get 'download_back', to: 'license_groups#download_back'
    end
  end
  resources :downloads do
    resources :download_musics
    get 'mp3_zip', to: 'download_musics#mp3_zip'
    get 'flac_zip', to: 'download_musics#flac_zip'
    resources :download_contents
  end
  devise_for :users
  root to: "home#index"
  get 'topic', to: 'home#topic'
  get 'use_card', to: 'home#use_card'
  get 'use_label', to: 'home#use_label'
  get 'use_make_card', to: 'home#use_make_card'
  get 'question', to: 'home#question'
  get 'contact', to: 'home#contact'
  post :contact, to: 'home#contact_confirm'
  post 'contact_create', to: 'home#contact_create'
  get 'contact_complete', to: 'home#contact_complete'
  get 'terms_of_service', to: 'home#terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    redirect_to "https://www.share-cards.com/", status: 301 if root_url == "https://share-cards.herokuapp.com/"
  end
  def topic
  end

  def use_card
  end

  def use_label
  end
  
  def use_make_card
  end
  
  def contact
    @contact = Contact.new()
  end

  def contact_confirm
    @contact = Contact.new(contact_params)
    render :contact if @contact.invalid?
  end

  def contact_create
    @contact = Contact.new(contact_params)

    if params[:back].present?
      render :contact
      return
    end

    @contact.save!

    ContactMailer.contact(@contact.title, @contact.email, @contact.content).deliver_now
    
    redirect_to contact_complete_path, notice: "送信されました。"
  end

  def contact_complete
    
  end

  def terms_of_service
  end

  def privacy_policy
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :email, :content)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<% if @contact.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
  <% @contact.errors.full_messages.each do |message| %>
  <%=message%><br>
  <%end%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<main>
  <div class="jumbotron jumbotron-fluid d-none d-md-block" style="background-image:url(<%= asset_path 'side-jumbotron.png' %>); height: 550px; background-position: center;">
    <div class="container" style="position: relative; top: 50%; transform: translateY(-50%);">
      <h1>お問い合わせ</h1>
    </div>
  </div>
  <div class="d-md-none my-5">
    <div class="container">
      <h1 style="font-size: 40px;">お問い合わせ</h1>
    </div>
  </div>
  <div class="container">
    <h2 class="text-center">お問い合わせフォーム</h2>
    <p>サービスに関してのご要望や質問などは以下のフォームより宜しくおねがいします。</p>
    <p>
    現在プレオープン中です。<br>
    サービスの正式スタート前にテスターとして使っていただける方を募集しております。<br>
    使っていただいて、よければ感想などをいただければと思います。<br>
    カード作成をする場合は、以下に<br><br>
    ○件名<br>
    ・カード作成用ユーザー登録について<br>
    ○メールアドレス<br>
    ・メールアドレス<br>
    ○お問い合わせ内容<br>
    ・ご希望のユーザー名<br>
    ・作成するカード枚数(予定)<br>
    ・用途<br>
    ・配布団体名(任意)<br>
    をご記入の上送信ください。<br>
    <br>
    ※詳しくは<%= link_to  "トピックス", topic_path %>も御覧ください。<br>
    登録状況にもより新規受付をしていない場合がありますがご了承ください。
    </p>
    <%=form_with model: @contact,url: {action: 'contact_confirm'}, local: true do |f|%>
      <div class="form-group">
        <%= f.label "件名" %>
        <%= f.text_field :title, class: "form-control", id: "title"%>
      </div>
      <div class="form-group">
        <%= f.label "メールアドレス" %>
        <%= f.text_field :email, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.label "お問い合わせ内容" %>
        <%= f.text_area :content, class: "form-control" %>
      </div>
      <div class="text-right">
        <%= f.submit "確認",class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>

app/views/home/contact_complete.html.erb
<main>
  <div class="jumbotron jumbotron-fluid d-none d-md-block" style="background-image:url(<%= asset_path 'side-jumbotron.png' %>); height: 550px; background-position: center;">
    <div class="container" style="position: relative; top: 50%; transform: translateY(-50%);">
      <h1>お問い合わせ</h1>
    </div>
  </div>
  <div class="d-md-none my-5">
    <div class="container">
      <h1 style="font-size: 40px;">お問い合わせ</h1>
    </div>
  </div>
  <div class="container">
    <h2 class="text-center">送信完了</h2>
    <p>お問い合わせありがとうございます。<br>メーセージは送信されました。</p>
    <%= link_to  "TOPに戻る", root_path,class: 'btn btn-primary btn-outline' %>
  </div>
</main>

app/views/home/contact_confirm.html.erb
<main>
  <div class="jumbotron jumbotron-fluid d-none d-md-block" style="background-image:url(<%= asset_path 'side-jumbotron.png' %>); height: 550px; background-position: center;">
    <div class="container" style="position: relative; top: 50%; transform: translateY(-50%);">
      <h1>お問い合わせ</h1>
    </div>
  </div>
  <div class="d-md-none my-5">
    <div class="container">
      <h1 style="font-size: 40px;">お問い合わせ</h1>
    </div>
  </div>
  <div class="container">
    <h2 class="text-center">確認画面</h2>
    <%=form_with model: @contact, url: contact_create_path, local: true do |f|%>
    <table class="table table-hover">
      <tbody>
        <tr>
          <th>件名</th>
          <td><%= @contact.title%></td>
          <%= f.hidden_field :title%>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @contact.email%></td>
          <%= f.hidden_field :email%>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td><%= @contact.content%></td>
          <%= f.hidden_field :content%>
        </tr>
      </tbody>
    </table>
      <div class="text-right">
        <%= f.submit "戻る", name: 'back',class: 'btn btn-primary btn-outline'%>
        <%= f.submit "送信", class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>

app/views/home/index.html.erb
<main>
  <div class="jumbotron jumbotron-fluid d-none d-md-block" style="background-image:url(<%= asset_path 'top-jumbotron.png' %>);background-size:cover; height: 60vw;">
    <div class="container" style="position: relative; top: 50%; transform: translateY(-50%);">
      <h1 style="line-height: 1.5;">お家でかんたん<br>ダウンロードカード制作</h1>
      <div>
        <%=link_to "ダウンロードする(カードが必要です)",downloads_path,class: "btn btn-raised btn-primary", style: "font-weight: bold;"%>
      </div>
      <div>
        <%=link_to "カードを作る",cards_path,class: "btn btn-outline btn-primary", style: "background-color: white; font-weight: bold;"%>
      </div>
    </div>
  </div>
  <div class="d-md-none my-5">
    <div class="container">
      <h1 style="font-size: 40px;">お家でかんたん<br>ダウンロードカード制作</h1>
      <div>
        <%=link_to "ダウンロードする(カードが必要です)",downloads_path,class: "btn btn-raised btn-primary", style: "font-weight: bold;"%>
      </div>
      <div>
        <%=link_to "カードを作る",cards_path,class: "btn btn-outline btn-primary", style: "background-color: white; font-weight: bold;"%>
      </div>
    </div>
  </div>
  <div class="container">
    <section class="mb-5">
      <div class="text-center">
        <h2 class="my-3">Shareを始めよう</h2>
        <div class="youtube mb-5">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/F51Mr42elVk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <h2 class="my-3">コンテンツを届ける新しいカタチ</h2>
        <%= image_tag  "top-img1.png" ,style: "max-width: 100%"%>
      </div>
      <div class="text-center">
        <p class="d-inline-block" style="text-align: left;">近年ではスマホで音楽を聞くことが主流となり、CDプレイヤーをもたない層が増加してます。<br>
        しかし、デジタル配信には手間がかかります。<br>
        <br>
        もっと手軽に、コンテンツを顧客に渡せられる方法はないでしょうか？<br>
        そんな問題を解決するのが「Share Cards」です。</p>
      </div>
    </section>
    <section class="mb-5">
      <div class="text-center">
        <h2 class="my-3">使い方</h2>
        <p class="mb-2">まずは市販の名刺カードを買います。</p>
        <div class="row mb-2">
          <div class="col-6">
            <%= image_tag  "a-one1.png" %>
          </div>
          <div class="col-6">
            <%= image_tag  "a-one2.png" %>
          </div>
        </div>
        <p class="d-inline-block" style="text-align: left;">
        対応用紙<br>
        Ａ－ＯＮＥ 名刺 マルチカード クリアエッジ 厚口 51861タイプ<br>
        Ａ－ＯＮＥ ラベルシール 44面 22シート 72244<br>
        など<br>
        ※「Ａ－ＯＮＥ」はスリーエム　カンパニーの商標または登録商標です。
        <%= link_to  "詳しくはこちら", question_path + '#compatible-paper' %>
        <div class="row mb-2">
          <div class="col-6">
            <span class="material-icons" style="font-size: 150px;">computer</span>
          </div>
          <div class="col-6 d-flex" style="align-items: center;">
            <p style="text-align: left;">
            その後WEBページを使用して、<br>
            レイアウトを作ります。</p>
          </div>
        </div>
        <div class="row mb-2">
          <div class="col-6">
            <span class="material-icons" style="font-size: 150px;">style</span>
          </div>
          <div class="col-6 d-flex" style="align-items: center;">
            <p style="text-align: left;">
            ダウンロードカードが出来ます</p>
          </div>
        </div>
        <div class="row mb-2">
          <div class="col-6">
            <span class="material-icons" style="font-size: 150px;">store</span>
          </div>
          <div class="col-6 d-flex" style="align-items: center;">
            <p style="text-align: left;">
            店頭でカードを販売します</p>
          </div>
        </div>
        <div class="row mb-2">
          <div class="col-6">
            <span class="material-icons" style="font-size: 150px;">accessibility</span>
          </div>
          <div class="col-6 d-flex" style="align-items: center;">
            <p style="text-align: left;">
            購入者はコンテンツをダウンロード出来ます</p>
          </div>
        </div>
        <p>※詳しい使い方は使い方ページを御覧ください</p>
        <%#= link_to  "使い方ページ", use_path %>
      </div>
    </section>
    <section class="mb-5">
      <div class="text-center">
        <h2 class="my-3">3つの特徴</h2>
        <div class="row">
          <div class="col-md-4 mb-3">
            <h4>さまざまなコンテンツ</h4>
            <%= image_tag  "top-img2.png" %>
            <p style="text-align: left;">さまざまなコンテンツを渡せます。<br>
            音楽・イラスト・写真・ゲームなど<br>
          </div>
          <div class="col-md-4 mb-3">
            <h4>限られた人数に共有できる</h4>
            <%= image_tag  "card_back.png" %>
            <p style="text-align: left;">
            カード一枚一枚に対して<br>
            Serial Codeを発行しています。<br>
            これにより、渡したい人だけにコンテンツを<br>
            渡すことが出来ます。
            </p>
          </div>
          <div class="col-md-4 mb-3">
            <h4>デザインを複数選べる(予定)</h4>
            <p style="text-align: left;">
            数種類の用意されたデザインの他<br>
            あなた独自のデザインを<br>
            選択することも出来ます。
            </p>
          </div>
        </div>
      </div>
    </section>
  </div>
  <div class="jumbotron jumbotron-fluid" style="background-color: #2196f3;">
    <div style="background-color: white; width: 300px; text-align: center; margin: 0 auto; padding: 20px 30px;">
      <h3>Shareを始めよう</h3>
      <p>
      今すぐカードを作って<br>
      コンテンツを送りましょう。
      </p>
      <div>
        <%=link_to "カードを作る",cards_path,class: "btn btn-raised btn-primary", style: "font-weight: bold;"%>
      </div>
    </div>
  </div>
</main>

app/views/home/question.html.erb
<main>
  <div class="jumbotron jumbotron-fluid d-none d-md-block" style="background-image:url(<%= asset_path 'side-jumbotron.png' %>); height: 550px; background-position: center;">
    <div class="container" style="position: relative; top: 50%; transform: translateY(-50%);">
      <h1>よくある質問</h1>
    </div>
  </div>
  <div class="d-md-none mb-5" style="padding-top: 50px;">
    <div class="container">
      <h1 style="font-size: 30px;">よくある質問</h1>
    </div>
  </div>
  <div class="container">
    <h3 id="serialcode-input">カードをSerialCodeの入力で登録したい</h3>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">カードをSerialCodeの入力で登録したい</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "use/smart-phone.jpg", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          <%= link_to  "登録ページ", rgs_path %>
          より新規登録できます。
          </p>
        </div>
      </div>
    </section>
    <h3 id="original-design">オリジナルデザインの作り方</h3>
    <p>
    ここでは代表的にPhotoshopとGIMPについて述べます。
    </p>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">1. Photoshopでの作り方</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/Photoshop1.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          【フォーマット番号：F10A4-1の場合】<br>
          Photoshop起動→新規作成より<br>
          ・幅 91mm <br>
          ・高さ 55mm <br>
          ・解像度 350ピクセル/インチ <br>
          ・RGBカラー <br>
          を設定し、作成をします。<br>
          すでに作成したテンプレートファイルもあります。<br>
          <a href="<%=root_url%>/question/F10A4-1.psd" download>【Photoshop-フォーマット番号：F10A4-1】</a>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/Photoshop2.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          絵柄を作成します。
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/Photoshop3.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          余白を設定します。<br>
          シェイプを選択し、2mmの外枠を作ります。<br>
          ※余白は白色である必要があります。<br>
          余白がなければ、柄がはみ出す事があります。
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/Photoshop4.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          完成です<br>
          デザインでフチを作っているので、フチはなしを選択します。
          </p>
        </div>
      </div>
      <h4 class="font-weight-bold mb-3 border-bottom">2. GIMP(無料)の場合</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/gimp.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          GIMPをダウンロード・インストールします。<br>
          <a href="https://www.gimp.org/downloads/" target="_blank">https://www.gimp.org/downloads/</a>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/gimp2.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          【フォーマット番号：F10A4-1の場合】<br>
          GIMP起動→新規作成より<br>
          ・幅 91mm <br>
          ・高さ 55mm <br>
          ・解像度 350ピクセル/インチ <br>
          ・RGBカラー <br>
          を設定し、作成をします。<br>
          すでに作成したテンプレートファイルもあります。<br>
          <a href="<%=root_url%>/question/F10A4-1.xcf" download>【GIMP-フォーマット番号：F10A4-1】</a>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/gimp3.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          余白の内側に柄を作成したら完成です。<br>
          デザインでフチを作っているので、フチはなしを選択します。
          </p>
        </div>
      </div>
    </section>
    <h3 id="compatible-paper">対応してるカード用紙は？</h3>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">1. カード用紙</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/F51002_O.jpg", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          現在A-oneの用紙に対応しています。<br>
          A-oneの用紙には余白の付き方によってフォーマット番号が振られております。<br><br>
          対応しているフォーマット番号は <span class="text-danger">【F10A4-1】</span>です。<br>
          必ずフォーマット番号をご確認ください。<br>
          また、<span class="text-danger">必ず白無地(色柄・透明柄は不可)</span>を使用してください。<br>
          ※色付きや透明柄はQRが読み取れない可能性があります。<br><br>
          【推奨用紙】<br>
          Ａ－ＯＮＥ 名刺 マルチカード クリアエッジ 厚口 51861タイプ<br>
          Ａ－ＯＮＥ マルチカード 名刺 厚口  51276
          ※「Ａ－ＯＮＥ」はスリーエム　カンパニーの商標または登録商標です。
          </p>
        </div>
      </div>
      <h4 class="font-weight-bold mb-3 border-bottom">2. ラベル用紙</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "question/F31262_O.jpg", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          現在A-oneの用紙に対応しています。<br>
          A-oneの用紙には余白の付き方によってフォーマット番号が振られております。<br><br>
          対応しているフォーマット番号は <span class="text-danger">【F44A4-1】</span>です。<br>
          必ずフォーマット番号をご確認ください。<br>
          また、<span class="text-danger">必ず白無地(色柄・透明柄は不可)</span>を使用してください。<br>
          ※色付きや透明柄はQRが読み取れない可能性があります。<br><br>
          【推奨用紙】<br>
          Ａ－ＯＮＥ ラベルシール 44面 22シート 72244
          ※「Ａ－ＯＮＥ」はスリーエム　カンパニーの商標または登録商標です。
          </p>
        </div>
      </div>
    </section>
  </div>
</main>

app/views/home/topic.html.erb
<main>
  <div class="jumbotron jumbotron-fluid d-none d-md-block" style="background-image:url(<%= asset_path 'side-jumbotron.png' %>); height: 550px; background-position: center;">
    <div class="container" style="position: relative; top: 50%; transform: translateY(-50%);">
      <h1>トピックス</h1>
    </div>
  </div>
  <div class="d-md-none mb-5" style="padding-top: 50px;">
    <div class="container">
      <h1 style="font-size: 30px;">トピックス</h1>
    </div>
  </div>
  <div class="container">
    <h3>トピックス</h3>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">2020/10/21 サービスをプレリリースしました</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "card_front.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>
          share cardsページをご覧下さってありがとうございます。<br>
          これは、しゅう(Twitter:@shu__pf)が個人で作成したWEBサービスになります。<br><br>
          このサービスは、CDが中心になっている同人界隈で、クリエイターがどうしたらCDを残したまま安価にダウンロード形式でもコンテンツ配布出来るだろうか？という事を考え作ったサービスです。<br><br>
          今回は、プレリリースという事でテスターとしてサービスを使っていただける方を募集しております。<br><br>
          これからの流れですが、<br>
          プレリリース期間<br>
          (お問い合わせより新規登録を受け付けます)<br>
          ※都合上カード制作アカウントの新規登録受付をやめる場合がありますがご了承ください。<br>
          ※視聴用アカウントは自由に登録できます<br>
          ↓<br>
          このサービスを続けて提供出来る事を目的として、広告などでの収益化、改良を加えた上で<br>
          正式サービス開始します<br>
          (プレリリース時で配布した物はそのままダウンロードできるようにする予定です)
          <br>
          <br>
          <%= link_to  "お問い合わせ", contact_path %>
          より新規登録できます。<br>
          よろしくお願いいたします。<br>
          </p>
        </div>
      </div>
    </section>
  </div>
</main>

app/views/home/use_card.html.erb
<main>
  <div class="jumbotron jumbotron-fluid d-none d-md-block" style="background-image:url(<%= asset_path 'side-jumbotron.png' %>); height: 550px; background-position: center;">
    <div class="container" style="position: relative; top: 50%; transform: translateY(-50%);">
      <h1>利用方法<br>カードを貰った</h1>
    </div>
  </div>
  <div class="d-md-none mb-5" style="padding-top: 50px;">
    <div class="container">
      <h1 style="font-size: 30px;">利用方法<br>カードを貰った</h1>
    </div>
  </div>
  <div class="container">
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">1. アカウントを作成します</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "use/login.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>初回利用の場合アカウントを作成をします</p>
        </div>
      </div>
    </section>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">2. カードの「QRコード」を読み取ります</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "card_back.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>カメラアプリを起動し、お持ちのカードの裏面に記載されております「QRコード」を読み取ります<br>
          ※読み取れない場合・PCでの登録の場合、手動で登録する事も可能です<br>
          詳しくは、<%=link_to "こちら",question_path + "#serialcode-input"%>を御覧ください</p>
        </div>
      </div>
    </section>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">3. カードを登録します</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "use/serialcode.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>QRコードにより、シリアルコードは自動入力されます。</p>
        </div>
      </div>
    </section>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">4. カードが登録されます</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "use/download-page.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>お持ちのカードが登録されます</p>
        </div>
      </div>
    </section>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">5. 詳細画面を開きます</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "use/download.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
        <div class="col-md-7">
          <p>ブラウザ上での音源の再生や、ダウンロードなど行えます</p>
        </div>
      </div>
    </section>
    <section class="mb-3">
      <h4 class="font-weight-bold mb-3 border-bottom">6. コンテンツを楽しみましょう</h4>
      <div class="row">
        <div class="col-md-5 mb-3">
          <%= image_tag "top-img2.png", class: "img-thumbnail", style: "object-fit: contain; height: 200px;" %>
        </div>
      </div>
    </section>
  </div>
</main>