config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  get 'admin/', to: 'admin#index'
  get 'admin/new_mail', to: 'admin#new_mail'
  post 'admin/send_mail', to: 'admin#send_mail'

  get 'rgs', to: 'rgs#index'
  get 'rgs/:serial_code', to: 'rgs#index'
  post 'rgs', to: 'rgs#rgs'
  
  resources :cards do
    get 'edit_title', to: 'cards#edit_title'
    get 'edit_auther_name', to: 'cards#edit_auther_name'
    get 'edit_content', to: 'cards#edit_content'
    get 'edit_card_img', to: 'cards#edit_card_img'
    resources :contents
    resources :musics do
      post 'moveup', to: 'musics#moveup'
      post 'movedown', to: 'musics#movedown'
      post 'music_destroy', to: 'musics#music_destroy'
    end
    resources :license_groups do
      get 'download', to: 'license_groups#download'
      get 'download_front', to: 'license_groups#download_front'
      get 'download_back', to: 'license_groups#download_back'
    end
  end
  resources :downloads do
    resources :download_musics
    get 'mp3_zip', to: 'download_musics#mp3_zip'
    get 'flac_zip', to: 'download_musics#flac_zip'
    resources :download_contents
  end
  devise_for :users
  root to: "home#index"
  get 'topic', to: 'home#topic'
  get 'use_card', to: 'home#use_card'
  get 'use_label', to: 'home#use_label'
  get 'use_make_card', to: 'home#use_make_card'
  get 'question', to: 'home#question'
  get 'contact', to: 'home#contact'
  post :contact, to: 'home#contact_confirm'
  post 'contact_create', to: 'home#contact_create'
  get 'contact_complete', to: 'home#contact_complete'
  get 'terms_of_service', to: 'home#terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  has_one_attached :card_img
  has_many :license_groups, dependent: :destroy
  has_many :contents, dependent: :destroy
  has_many :musics, dependent: :destroy

  validates :title, presence: true
  validates :format, presence: true
  validates :auther_name, presence: true
  validates :card_img, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :if_not_creator

  def index
    @cards = current_user.cards
  end

  def new_music
  end

  def edit_title
    @card = Card.find_by(id: params[:card_id], user_id: current_user.id)
  end

  def edit_auther_name
    @card = Card.find_by(id: params[:card_id], user_id: current_user.id)
  end

  def edit_card_img
    @card = Card.find_by(id: params[:card_id], user_id: current_user.id)
  end

  def update
    card = Card.find_by(id: params[:id], user_id: current_user.id)
    flag = card.update(card_params)
    if flag
    else
      redirect_to card_url(card), alert: "更新に失敗しました"
      return
    end
    redirect_to card_url(card), notice: "更新しました。"
  end

  def edit
    @card = Card.find_by(id: params[:id], user_id: current_user.id)
  end

  def show
    @card = current_user.cards.find(params[:id])
  end

  def destroy
    card = Card.find_by(id: params[:id], user_id: current_user.id)
    card.destroy!
    redirect_to cards_url
  end

  def select
  end

  def new
    @card = Card.new()
    @license_group = LicenseGroup.new()
  end

  def create
    @card = Card.new(card_params)
    @card[:user_id] = current_user.id
    case @card.design_type
    when 2 then
      downloaded_image = open(root_url + 'samplecard1.png')
      @card.card_img.attach(io: downloaded_image  , filename: "samplecard1.png")
    end

    if @card.save == false
      render :new
      return
    end

    redirect_to card_url(@card), notice: "作成されました。続いてコンテンツを登録します。"
  end

  private

  def card_params
    if params[:card]
      params.require(:card).permit(:title, :auther_name, :card_img, :design_type, :format, :edge_blank)
    else
      # ActiveStrageがからの場合の処理
      # とりあえずなので要修正
      params[:card] = {title: ""}
    end
  end

  def if_not_creator
    redirect_to root_url, notice: "現在は視聴専用のユーザーです。カードは作成出来ません。カードを作成するにはお問い合わせください。" unless current_user.creator?
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<% if @card.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
  <% @card.errors.full_messages.each do |message| %>
  <%=message%><br>
  <%end%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<main>
  <div class="container">
    <h2 class="my-3">カード編集画面</h2>
    <%=form_with model: @card, local: true do |f|%>
      <div class="form-group">
        <%= f.label "タイトル" %>
        <%= f.text_field :title, class: "form-control", id: "title"%>
      </div>
      <div class="form-group">
        <%= f.label "作成者" %>
        <%= f.text_field :auther_name, class: "form-control", id: "auther_name"%>
      </div>
      <div class="form-group">
        <%= f.label "コンテンツ" %>
        <%= f.file_field :content, class: "form-control-file", id: "content"%>
      </div>
      <h3>表面のデザイン設定</h3>
      <div class="form-group">
        <%= f.label "カードの表の背景(1254px*758px)" %>
        <%= f.file_field :card_img, class: "form-control-file", id: "card_img"%>
      </div>
      <div class="text-center">
        <%= image_tag 'sample.png', id: "background-preview", style: "max-width: 100%; max-height: 379px;" %>
      </div>
      <div class="text-right">
        <%= f.submit nil,class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>
<%= javascript_pack_tag 'cards', 'data-turbolinks-track': 'reload' %>

app/views/cards/edit_auther_name.html.erb
<% if @card.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
  <% @card.errors.full_messages.each do |message| %>
  <%=message%><br>
  <%end%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<main>
  <div class="container">
    <h2 class="my-3">作者名の編集</h2>
    <%=form_with model: @card, local: true do |f|%>
      <div class="form-group">
        <%= f.label "作成者" %>
        <%= f.text_field :auther_name, class: "form-control", id: "auther_name"%>
      </div>
      <div class="text-right">
        <%= f.submit nil,class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>
<%= javascript_pack_tag 'cards', 'data-turbolinks-track': 'reload' %>

app/views/cards/edit_card_img.html.erb
<% if @card.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
  <% @card.errors.full_messages.each do |message| %>
  <%=message%><br>
  <%end%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<main>
  <div class="container">
    <h2 class="my-3">デザインの編集</h2>
    <%=form_with model: @card, local: true do |f|%>
      <div class="form-group">
        <%= f.label "カードの表の背景(1254px*758px)" %>
        <%= f.file_field :card_img, class: "form-control-file", id: "card_img"%>
      </div>
      <div class="text-right">
        <%= f.submit nil,class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>
<%= javascript_pack_tag 'cards', 'data-turbolinks-track': 'reload' %>

app/views/cards/edit_content.html.erb
<% if @card.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
  <% @card.errors.full_messages.each do |message| %>
  <%=message%><br>
  <%end%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<main>
  <div class="container">
    <h2 class="my-3">コンテンツの編集</h2>
    <%=form_with model: @card, local: true do |f|%>
      <div class="form-group">
        <%= f.label "コンテンツ" %>
        <%= f.file_field :content, class: "form-control-file", id: "content"%>
      </div>
      <div class="text-right">
        <%= f.submit nil,class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>
<%= javascript_pack_tag 'cards', 'data-turbolinks-track': 'reload' %>

app/views/cards/edit_title.html.erb
<% if @card.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
  <% @card.errors.full_messages.each do |message| %>
  <%=message%><br>
  <%end%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<main>
  <div class="container">
    <h2 class="my-3">タイトルの編集</h2>
    <%=form_with model: @card, local: true do |f|%>
      <div class="form-group">
        <%= f.label "タイトル" %>
        <%= f.text_field :title, class: "form-control", id: "title"%>
      </div>
      <div class="text-right">
        <%= f.submit nil,class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>
<%= javascript_pack_tag 'cards', 'data-turbolinks-track': 'reload' %>

app/views/cards/index.html.erb
<main>
  <div class="container">
    <h2 class="my-3" style="color: #2196f3;"><span class="material-icons">info</span>カード管理画面</h2>
    <div class="d-md-none">
      <% @cards.each do |card| %>
      <div class="row mb-2 border-top pt-2">
        <div class="col-4">
          <div class="pr-1 text-center">
            <%= image_tag card.card_img.variant(resize:'140x100').processed, class: "img-thumbnail", style: "object-fit: contain;" if card.card_img.attached? %>
          </div>
        </div>
        <div class="col-8">
          <h4><%=card.title%></h4>
          <p style="margin-bottom: 3px;"><%=card.auther_name%></p>
          <div class="text-right">
            <%= link_to "詳細", card_path(card) ,class: "btn btn-primary btn-outline btn-sm"%>
            <%= link_to "削除", card ,class: "btn btn-danger btn-outline btn-sm", method: :delete, data: { confirm: "削除してもよろしいですか？"} %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="d-none d-md-block">
      <div class="row">
      <% @cards.each do |card| %>
        <div class="col-md-4 mb-3">
          <div class="card" style="max-width: 25rem;">
            <%= image_tag card.card_img.variant(resize:'350x200').processed, class: "card-img-top", style: "object-fit: contain;height: 200px;" if card.card_img.attached? %>
            <div class="card-body">
              <h4 class="card-title"><%=card.title%></h4>
              <h6 class="card-subtitle"><%=card.auther_name%></h6>
              <p class="card-text"></p>
              <div class="text-right">
                <%= link_to "詳細", card_path(card) ,class: "btn btn-primary btn-outline btn-sm"%>
                <%= link_to "削除", card ,class: "btn btn-danger btn-outline btn-sm", method: :delete, data: { confirm: "本当に削除してもよろしいですか？(カードのコンテンツと、カードの全てのシリアルコードが削除されます)"} %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <% if @cards.empty? %>
    <div class="text-center my-5">
      <h3><span class="material-icons" style="font-size: 4rem;">help</span></h3>
      <h4>まだカードを作成していません。</h4>
      <p>
      初めてご利用になりますか？
      <%=link_to "作成方法を御覧ください", use_make_card_path,class: "btn btn-outline btn-primary", style: "font-weight: bold;", :target=>["_blank"]%>
      </p>
    </div>
    <% end %>
    <div class="text-right mb-3">
      <%=link_to "カードテンプレートの作成", new_card_path, class: "btn btn-primary btn-raised"%>
    </div>
  </div>
</main>

app/views/cards/new.html.erb
<% if @card.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
  <% @card.errors.full_messages.each do |message| %>
  <%=message%><br>
  <%end%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<main>
  <div class="container">
    <h2 class="my-3">新しいカードテンプレートの作成</h2>
    <%= link_to  "戻る", cards_path, class: "btn btn-primary btn-outline mb-3" %>
    <%=form_with model: @card, local: true do |f|%>
      <div class="form-group">
        <%= f.label "タイトル" %>
        <%= f.text_field :title, class: "form-control", id: "title"%>
      </div>
      <div class="form-group">
        <%= f.label "作成者" %>
        <%= f.text_field :auther_name, class: "form-control", id: "auther_name"%>
      </div>
      <h3>デザイン設定</h3>
      <p>カードのデザインを決められます。</p>
      <p>
      オリジナルのデザインの場合は、「<%= link_to  "オリジナルデザインの作り方", question_path + '#compatible-paper' %>」を御覧ください。<br>
      特に画像をカード向けに加工しなくても使うことも可能です。<br>
      その場合、例えば縦長の画像の場合は左右に隙間が空きます。<br>
      また「フチあり」を選択してください。
      </p>
      <p>※用紙設定でラベルの商品を選んだ場合、この設定はラベル印刷面には現れません。(ダウンロードページや管理画面では使われます)</p>
      <div class="form-group">
        <%= f.label "用紙選択" %>
        <%= f.select :format, {'A-one フォーマット番号【F10A4-1】' => "F10A4-1", 'A-one フォーマット番号【F44A4-1】(ラベル商品)' => "F44A4-1"},{}, class: "custom-select", id: "format"%>
      </div>
      <div class="form-group">
        <%= f.label "デザインの選択" %>
        <%= f.select :design_type, {'オリジナルのデザイン' => 1, 'プリセット1' => 2},{}, class: "custom-select", id: "design_type"%>
      </div>
      <div class="form-group">
        <%= f.label "デザインのアップロード" %>
        <%= f.file_field :card_img, class: "form-control-file", id: "card_img"%>
      </div>
      <div class="form-check">
        <%= f.check_box :edge_blank, class: "form-check-input", id: "edge_blank"%>
        <%= f.label "フチあり", class: "form-check-label" %>
      </div>
      <h4 class="my-3">デザインプレビュー</h4>
      <div class="text-center">
        <div class="border d-inline-block" style="width: 100%; padding-top: 60%; position: relative;">
          <%= image_tag 'sample.png', id: "background-preview", style: "width: 100%; height: 100%; position: absolute; top: 0; left: 0; object-fit: contain; height: 99%;" %>
        </div>
      </div>
      <div class="text-right">
        <%= f.submit nil,class: 'btn btn-primary btn-raised'%>
      </div>
    <%end%>
  </div>
</main>
<%= javascript_pack_tag 'cards', 'data-turbolinks-track': 'reload' %>

app/views/cards/show.html.erb
<main>
  <div class="container">
    <h2 class="my-3"><%=@card.title%></h2>
    <h5><%=@card.auther_name%></h5>
    <%=link_to "一覧画面に戻る", cards_path, class: "btn btn-primary btn-outline"%>
    <div class="text-center mb-3">
      <%= image_tag @card.card_img.variant(resize:'1600x379').processed, style: "max-width: 100%; max-height: 379px;" if @card.card_img.attached? %>
    </div>
    <div class="text-right mb-3">
      <%=link_to "カードデザインを変更する" , card_edit_card_img_path(@card), class: "btn btn-success btn-outline"%>
    </div>
    <section>
      <h4>カード情報</h4>
      <table class="table table-hover">
        <tbody>
          <tr>
            <td>作成日時</td>
            <td><%=@card.created_at.to_s(:datetime_jp)%></td>
            <td>
            </td>
          </tr>
          <tr>
            <td>タイトル</td>
            <td><%=@card.title%></td>
            <td>
              <div class="text-right">
                <%=link_to "編集", card_edit_title_path(@card), class: "btn btn-success btn-outline"%>
              </div>
            </td>
          </tr>
          <tr>
            <td>作者名</td>
            <td><%=@card.auther_name%></td>
            <td>
              <div class="text-right">
                <%=link_to "編集", card_edit_auther_name_path(@card), class: "btn btn-success btn-outline"%>
              </div>
            </td>
          </tr>
          <tr>
            <td>用紙タイプ</td>
            <td><%=@card.format%></td>
            <td>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
    <section>
      <h4>楽曲・音声</h4>
      <table class="table table-hover">
        <tbody>
          <% @card.musics.order(track_number: "ASC").each do |music| %>
          <tr>
            <td><%=music.track_number%></td>
            <td><%=music.title%></td>
          </tr>
          <%end%>
        </tbody>
      </table>
      <%if @card.musics.any? == false%>
        <h5 class="text-center">まだ登録されてません</h5>
      <%end%>
      <div class="text-right mb-3">
        <%=link_to "詳細設定" , card_musics_path(@card), class: "btn btn-primary btn-outline"%>
      </div>
    </section>
    <section>
      <h4>コンテンツ</h4>
      <table class="table table-hover">
        <tbody>
        <%@card.contents.each do |content|%>
          <tr>
            <td><%=content.content.filename.to_s%></td>
            <td>
              <div class="text-right">
                <%=link_to "削除", card_content_path(@card, content), method: :delete, class: "btn btn-danger"%>
              </div>
            </td>
          </tr>
        <%end%>
        </tbody>
      </table>
      <%if @card.contents.any? == false%>
        <h5 class="text-center">まだ登録されてません</h5>
      <%end%>
      <div class="text-right mb-3">
        <%=link_to "コンテンツを追加登録する" , new_card_content_path(@card), class: "btn btn-primary btn-outline"%>
      </div>
    </section>
    <section>
      <h4>シリアルコード付きカードの再印刷と新規作成</h4>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">作成日時</th>
            <th scope="col">カード枚数</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @card.license_groups.each do |license_group| %>
          <tr>
            <td><%=license_group.created_at.to_s(:datetime_jp)%></td>
            <td><%=license_group.number_of_licenses%></td>
            <td>
              <div class="text-right">
                <%=link_to "再印刷", card_license_group_download_path(@card, license_group), class: "btn btn-primary btn-raised"%>
                <%=link_to "削除", card_license_group_path(@card, license_group),method: :delete , class: "btn btn-danger", data: { confirm: "本当に削除してもよろしいですか？既にカードを配布している場合はそのカードは使用出来なくなります。"}%>
              </div>
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
      <div class="text-right mb-3">
        <%=link_to "追加作成する" ,new_card_license_group_path(@card), class: "btn btn-primary btn-outline"%>
      </div>
    </section>
  </div>
</main>